python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 8eb971 ../public/textures/1.0/blocks/grass_block_top_oceans.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 91bd59 ../public/textures/1.0/blocks/grass_block_top_plains.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png bfb755 ../public/textures/1.0/blocks/grass_block_top_desert.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 8ab689 ../public/textures/1.0/blocks/grass_block_top_extreme_hills.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 79c05a ../public/textures/1.0/blocks/grass_block_top_forest.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 86b87f ../public/textures/1.0/blocks/grass_block_top_taiga.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 5c694e ../public/textures/1.0/blocks/grass_block_top_swampland.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 8eb971 ../public/textures/1.0/blocks/grass_block_top_river.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png bfb755 ../public/textures/1.0/blocks/grass_block_top_nether.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 8eb971 ../public/textures/1.0/blocks/grass_block_top_end.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 80b497 ../public/textures/1.0/blocks/grass_block_top_frozen_oceans.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 80b497 ../public/textures/1.0/blocks/grass_block_top_frozen_river.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 80b497 ../public/textures/1.0/blocks/grass_block_top_ice_plains.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 80b497 ../public/textures/1.0/blocks/grass_block_top_ice_mountains.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 55c93f ../public/textures/1.0/blocks/grass_block_top_mushroom_island.png
python grass_block_top.py ../public/textures/1.0/blocks/grass_block_top_gray.png 55c93f ../public/textures/1.0/blocks/grass_block_side_mushroom_island_shore.png

python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 8eb971 ../public/textures/1.0/blocks/grass_block_side_oceans.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 91bd59 ../public/textures/1.0/blocks/grass_block_side_plains.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png bfb755 ../public/textures/1.0/blocks/grass_block_side_desert.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 8ab689 ../public/textures/1.0/blocks/grass_block_side_extreme_hills.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 79c05a ../public/textures/1.0/blocks/grass_block_side_forest.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 86b87f ../public/textures/1.0/blocks/grass_block_side_taiga.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 5c694e ../public/textures/1.0/blocks/grass_block_side_swampland.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 8eb971 ../public/textures/1.0/blocks/grass_block_side_river.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png bfb755 ../public/textures/1.0/blocks/grass_block_side_nether.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 8eb971 ../public/textures/1.0/blocks/grass_block_side_end.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 80b497 ../public/textures/1.0/blocks/grass_block_side_frozen_oceans.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 80b497 ../public/textures/1.0/blocks/grass_block_side_frozen_river.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 80b497 ../public/textures/1.0/blocks/grass_block_side_ice_plains.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 80b497 ../public/textures/1.0/blocks/grass_block_side_ice_mountains.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 55c93f ../public/textures/1.0/blocks/grass_block_side_mushroom_island.png
python grass_block_side.py ../public/textures/1.0/blocks/grass_block_side.png 55c93f ../public/textures/1.0/blocks/grass_block_side_mushroom_island_shore.png
